### PR TITLE
default.xml: update meta-lmp layer

### PR DESCRIPTION
**Pull request by mbolivar**
Bring in an HSM-based lmp-device-register.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Mind removing the 'Change-Id: I0efe0ef2ab2e2456a0eddc3e6df6402d6faa31a4' line from your commit message?

**Comment by mbolivar** [comment]
I will try. God, here we go; I remember repo's hooks are harder to kill than cockroaches...

**Comment by mbolivar** [comment]
DOne

**Comment by mbolivar** [comment]
DNM, needs rework for non-HSM provisioning

**Comment by mbolivar** [comment]
ci-retest

**Comment by mbolivar** [comment]
ci-retest

**Comment by mbolivar** [comment]
OK, includes the regression fix

**Comment by ricardosalveti** [comment]
ci-retest

**Pull request merged**
