### PR TITLE
MX6/MX8 BSP update

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
ci-retest

**Review by MrCry0 — APPROVED** [review]
Need to be rebased on top of https://github.com/foundriesio/meta-lmp/pull/943

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
