### PR TITLE
Update some layers

### PR DESCRIPTION
**Pull request by angolini**
lmp-base: update meta-lts-mixins-go layer
lmp-base: update openembedded-core layer
lmp-base: update meta-lmp layer

### CODE REVIEW

**Review by quaresmajose — APPROVED** [review]

**Comment by quaresmajose** [comment]
Hold one! The meson from https://github.com/foundriesio/meta-lmp/commit/c8db41e5083eb487119f8eb7e969cae5ceb00e34 is in use everywhere and not only on imx8 and imx9

**Comment by quaresmajose** [comment]
Fixup the imx meson backported https://github.com/foundriesio/meta-lmp/pull/1479

**Comment by quaresmajose** [comment]
@angolini can you please add the https://github.com/foundriesio/meta-lmp/commit/915af2cee6342e690db16592265e43bab300d97b

**Review by quaresmajose — CHANGES_REQUESTED** [review]
the build completed successfully but I noticed that there was a typo on the commit title `base -> lmp-base`

**Comment by angolini** [comment]
@quaresmajose done

**Review by quaresmajose — APPROVED** [review]
LGTM

**Pull request merged**
