### PR TITLE
Xilinx BSP 2022.1 Update 

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
@igoropaniuk can you give kria a try to make sure we didn't cause any regression?

@ldts can you check vck190-versal as well? This is with the 2022.1 Xilinx BSP release.

**Comment by ricardosalveti** [comment]
@quaresmajose still using my own meta-lmp (until it gets merged), but this is the current hash used by honister, which should be the starting point for the kirk porting.

**Comment by quaresmajose** [comment]
@ricardosalveti I will use this as a starting point for the porting

**Review by quaresmajose — APPROVED** [review]

**Review by igoropaniuk — APPROVED** [review]
LGTM
Also tested on Kria kv260

**Pull request merged**
