### PR TITLE
setup-environment-internal: adjust target suggestions

### PR DESCRIPTION
**Pull request by igoropaniuk**
Print different lmp-mfgtool target suggestions depending on machine.

Change-Id: Ief0b2c4f70b75af7fbd07f2c237c4fc6c91b4fb2

### CODE REVIEW

**Comment by quaresmajose** [comment]
why we need the gerrit `Change-Id: Ief0b2c4f70b75af7fbd07f2c237c4fc6c91b4fb2`?

**Comment by ricardosalveti** [comment]
Please drop change-id from the commit message.

**Comment by igoropaniuk** [comment]
I was committing directly in `<lmp.repo>/.repo/manifests`, and looks like there is commit-msg hook configured to add `change-id`

Removed it

**Review by quaresmajose — APPROVED** [review]

**Review by ricardosalveti — APPROVED** [review]
LGTM, will merge together with our next lmp-manifest bump to avoid another build / test round.

**Comment by quaresmajose** [comment]
merged in https://github.com/foundriesio/lmp-manifest/pull/369

**Pull request closed without merging**
