### PR TITLE
Hardknott updates

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
@angolini @vanmaegima @Tim-Anderson @mike-scott also good for initial review, goal is to merge in master-next (after meta-lmp gets merged there as well).

**Comment by angolini** [comment]
`raspberrypi4-64` and `imx6ullevk-sec` tested and working

**Comment by vanmaegima** [comment]
`imx6ullevk` and `apalis-imx6` tested and working

**Comment by ricardosalveti** [comment]
Manually merged to avoid extra builds, will create a larger jira tomorrow so we can track the remaining test items.

**Pull request closed without merging**
