### PR TITLE
Stable updates for v90 rc2

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
> Could we include them to the release?

Should be fine, let me have a look. @quaresmajose for go we need to make sure the mixins layer is also updated if affected.

**Comment by ricardosalveti** [comment]
Go seems to be a backport from 1.19, so we should be fine, but good to double check.

**Comment by ricardosalveti** [comment]
> > > Could we include them to the release?
> > 
> > 
> > Should be fine, let me have a look. @quaresmajose for go we need to make sure the mixins layer is also updated if affected.
> 
> There are one new commit on the mixins layer that I backport yesterday so the mixins can also be updated.

At least latest on https://github.com/foundriesio/meta-lts-mixins is from 2 weeks ago, need to check if the mirroring is ok there.

**Comment by quaresmajose** [comment]
> > > > Could we include them to the release?
> > > 
> > > 
> > > Should be fine, let me have a look. @quaresmajose for go we need to make sure the mixins layer is also updated if affected.
> > 
> > There are one new commit on the mixins layer that I backport yesterday so the mixins can also be updated.
> 
> At least latest on https://github.com/foundriesio/meta-lts-mixins is from 2 weeks ago, need to check if the mirroring is ok there.

We have switched to use the upstream repo that is available in our mirror and it includes the last commit.

https://github.com/lmp-mirrors/meta-lts-mixins/commits/kirkstone/go

**Comment by ricardosalveti** [comment]
I will bump to the latest there together with a few other minor lmp changes that I'm checking now.

**Comment by quaresmajose** [comment]
> Right, we should archive https://github.com/foundriesio/meta-lts-mixins then.

The PR for that is already open https://github.com/foundriesio/meta-lts-mixins/pull/1

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
