### PR TITLE
Stm32 Trusted Boot

### PR DESCRIPTION
**Pull request by ricardosalveti**
Testing https://github.com/foundriesio/lmp-manifest/pull/229 and https://github.com/foundriesio/meta-lmp/pull/847.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
ci-retest

**Review by quaresmajose — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
