### PR TITLE
lmp-bsp: update meta-tegra layer

### PR DESCRIPTION
**Pull request by MrCry0**
- `meta-tegra` includes the latest changes in kirkstone
 ̶-̶ ̶m̶e̶t̶a̶-̶l̶m̶p̶ ̶i̶n̶c̶l̶u̶d̶e̶s̶ ̶f̶i̶x̶e̶s̶ ̶f̶o̶r̶ ̶m̶e̶t̶a̶-̶t̶e̶g̶r̶a̶ ̶a̶n̶d̶ ̶o̶e̶-̶c̶o̶r̶e̶ ̶(̶e̶x̶c̶e̶p̶t̶ ̶o̶f̶ ̶a̶m̶6̶x̶x̶x̶x̶ ̶i̶s̶u̶e̶e̶ ̶w̶i̶t̶h̶ ̶s̶p̶d̶x̶)̶

### CODE REVIEW

**Comment by quaresmajose** [comment]
This is also broken on main-next and I am on it, when fixed I backport the patches to kirkstone

**Comment by quaresmajose** [comment]
Fixed with https://github.com/foundriesio/meta-lmp/pull/1002

**Comment by quaresmajose** [comment]
> Fixed with [foundriesio/meta-lmp#1002](https://github.com/foundriesio/meta-lmp/pull/1002)

@MrCry0  [foundriesio/meta-lmp#1002](https://github.com/foundriesio/meta-lmp/pull/1002) is merged so can you please rebase and also update the layers:

meta-lmp [b16da27a](https://github.com/foundriesio/meta-lmp/commit/b16da27a869414bff9332b4952f0dab100eca6c1) 
meta-tegra [d3b89844](https://github.com/OE4T/meta-tegra/commit/d3b89844da84a625086baa4fba1b36d97036f5ec)

**Comment by MrCry0** [comment]
> Fixed with [foundriesio/meta-lmp#1002](https://github.com/foundriesio/meta-lmp/pull/1002)

I updated the PR, let's just wait :)

**Comment by quaresmajose** [comment]
I prefer to not merge the clang fixes in this PR because they are not need to bump meta-tegra and we don't know yet where it is introduced in oe-core
```
- f698342e base: non-clangable: don't use llvm-strip in the kernel
- b54bf470 base: non-clangable: don't use llvm-objcopy in the kernel
- 3926dfcd base: non-clangable: u-boot: force gcc
```

**Comment by MrCry0** [comment]
> I prefer to not merge the clang fixes in this PR because they are not need to bump meta-tegra and we don't know yet where it is introduced in oe-core

Well, it should break nothing, as before the bug was introduced in oe-core we still hadn't used clang tools for kernel

**Comment by quaresmajose** [comment]
> Well, it should break nothing, as before the bug was introduced in oe-core we still hadn't used clang tools for kernel.
> 
> But you may be right, the atomic rule is against such bumping. I'm dropping these changes.

Think again I can be a wast of time building this again on CI and as this is now merged in meta-lmp we can go with it and I can revert this meta-lmp changes locally to find the root cause of them in oe-core.

**Review by quaresmajose — APPROVED** [review]
LGTM

**Comment by MrCry0** [comment]
@ricardosalveti don't you mind?

**Comment by ricardosalveti** [comment]
@MrCry0 we updated meta-lmp as part of the meta-ti bump, so we can just update meta-tegra here.

**Comment by MrCry0** [comment]
@ricardosalveti updated

**Comment by quaresmajose** [comment]
The latest a20e9664 meta-tegra kirkstone needs some adaptation needs some adaptation that I am fixing now.
The last revision of this bump d3b89844 is ok to merge.

**Comment by quaresmajose** [comment]
> The latest a20e9664 meta-tegra kirkstone needs some adaptation that I am fixing now.
> The last revision of this bump d3b89844 is ok to merge.

@MrCry0 Fixed with https://github.com/foundriesio/meta-lmp/pull/1012

**Review by quaresmajose — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
Will merge this one and create another pr for bumping to the latest tegra/lmp.

**Pull request merged**
