### PR TITLE
Pull in new meta-lmp

### PR DESCRIPTION
**Pull request by doanac**
This pull in the latest meta-lmp as well as updates to aktualizr
that rebase cleanly on top of it.

Changes to meta-lmp:

b056b70 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #591 from advancedtelematic/fix/ip-secondary-test/wait-until-provisioned
620152f Use --wait-until-provisioned option while getting aktualizr status in the ip secondary tests
abfc287 Merge pull request #590 from advancedtelematic/fix/OTA-3419/garage-sign-expiry
74d9d16 README: new section for garage-sign.
08759ff Use a default expiry of one month if nothing is specified.
8434da1 aktualizr: latest garage-sign with expiration support.
3bc6500 Merge pull request #587 from advancedtelematic/fix/grub-ostree
f865c40 Expose OSTREE_BOOT_PARTITION in do_image_ota
e8ec175 Merge pull request #586 from advancedtelematic/fix/ptest-qa
1b46307 Fix error during package_qa with aktualizr-ptest
8b4f0cf Fix/ostree branchname 2 (#585)
261c28a Do not export anything in sota.bbclass
4f90284 Revert "Move OSTREE_BRANCHNAME to image_types_ostree.bbclass."
057fdb0 Merge pull request #532 from advancedtelematic/feat/OTA-2666/garage-tools-mutual-tls
8fa3a60 Bump aktualizr and garage-sign versions to the latest.
9921803 Merge pull request #578 from advancedtelematic/fix/qemucommand
c6ad1d2 qemucommand.py: redirect qemu monitor to null chardev
b8215f4 Merge pull request #572 from advancedtelematic/test/ota-3064/test-for-setting-custom-hardware-id
a2fc4db Test for setting hwid
558c25c Revert "Do not create connman's resolv.conf symlink at boot" (#577)
1a3c0f0 Revert "Do not create connman's resolv.conf symlink at boot"
f348e80 Merge pull request #574 from advancedtelematic/connman-fix-master
8b5e97c Bump aktualizr
36f3119 More helpful error message when running qemu
8180fe8 Add bugfix service for old connman to systemd-networkd
2c72b0c Do not create connman's resolv.conf symlink at boot
cf559d5 Merge pull request #568 from advancedtelematic/feat/OTA-3115/Dont-patch-credentials
672fcc5 Dont patch credentials

Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
@rsalveti - this is more of a test to make sure my aktualizr patches are applied cleanly and work so that i can do a PR for: https://github.com/foundriesio/meta-lmp/commit/03ecda1ffd61d6f3116e7223bedb305777f28960 However, if things look good I guess this might be mergable?

Note - there are some networking related stuff with conman in this change log. Not sure it affects us.

**Comment by doanac** [comment]
ci-retest - looks good, but the job didn't pick up a new OTA_LITE_TAG parameter. This should do the trick

**Comment by doanac** [comment]
ci-retest - this time the params will get passed

**Comment by doanac** [comment]
This pulls in what I was needing fixed in aktualizr-lite. I've tested and put the actual meta-lmp change into a PR now. Once merged, we can can update this to match the new SHA and merge this if it looks correct.

**Comment by ricardosalveti** [comment]
Now part of #28

**Pull request closed without merging**
