### PR TITLE
Include ebbr-nxp changes w/o switching to net bsp and update freescale layers

### PR DESCRIPTION
**Pull request by MrCry0**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Meta-lmp change can be dropped, I updated in order to add allwinner support.

**Comment by ricardosalveti** [comment]
I think this won't update u-boot and kernel, but will probably update the rest (atf, gstreamer, etc), which should be ok until we land the rest.

**Comment by MrCry0** [comment]
> Meta-lmp change can be dropped, I updated in order to add allwinner support.

I'm not sure I understood you correctly. I don't see these changes :(

**Comment by ricardosalveti** [comment]
Should be https://github.com/foundriesio/lmp-manifest/commit/c6e11103635971b85138367dcfbb5f4da5e787f1

**Comment by MrCry0** [comment]
> Should be [c6e1110](https://github.com/foundriesio/lmp-manifest/commit/c6e11103635971b85138367dcfbb5f4da5e787f1)

Ah, I constantly forget about this direct committing practice :)

**Comment by ricardosalveti** [comment]
> > Should be [c6e1110](https://github.com/foundriesio/lmp-manifest/commit/c6e11103635971b85138367dcfbb5f4da5e787f1)
> 
> Ah, I constantly forget about this direct committing practice :)

Yeah, my bad, I should stop doing that now that we got more reviewers :-)

**Comment by MrCry0** [comment]
> I think this won't update u-boot and kernel, but will probably update the rest (atf, gstreamer, etc), which should be ok until we land the rest.

@ricardosalveti Well, I seem to lost one commit for imx-atf :( in meta-lmp https://github.com/foundriesio/meta-lmp/pull/504

**Comment by MrCry0** [comment]
This wont' work without switching to 2021.04+5.10, so I'm closing it.

**Pull request closed without merging**
