### PR TITLE
Stable update (oe-core after rm_work issue and the other requirement)

### PR DESCRIPTION
**Pull request by quaresmajose**

### CODE REVIEW

**Comment by quaresmajose** [comment]
ci-retest

**Comment by quaresmajose** [comment]
ci-retest

**Comment by quaresmajose** [comment]
ci-retest

**Comment by quaresmajose** [comment]
ci-retest

**Comment by quaresmajose** [comment]
ci-retest

**Comment by quaresmajose** [comment]
ci-retest

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
