### PR TITLE
lmp-base: update meta-lmp layer

### PR DESCRIPTION
**Pull request by igoropaniuk**
Relevant changes:
4697b61 base: u-boot-fio: 2020.04: bump to dbb9acc4eb
f44f301 base: u-boot-fio: 2020.04: bump to c8e17fe087
3d0816b bsp: mfgtool-files: imx8mmevk: add flashing of secondary boot images
73ae186 imx-boot: add SIT image build
fb13646 u-boot-fio: imx8mmevk: add support for secondary boot images
623208c base: u-boot: set u-boot localversion string
fed052c base: add fio-u-boot-localversion.bbclass
28237f4 optee: add configuration for 3.12

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

### CODE REVIEW

**Review by mike-scott — COMMENTED** [review]
Builds look green.  I can test imx8mmevk in a bit.

**Comment by ricardosalveti** [comment]
I think we're only missing the ci-scripts change to publish the new binaries. Once that is done we can merge this one.

**Comment by igoropaniuk** [comment]
https://github.com/foundriesio/ci-scripts/pull/119

**Comment by igoropaniuk** [comment]
iMX8MQ-EVKB boots:
```
-Boot 2020.04+fio+gdbb9acc4eb (Jan 01 1970 - 00:00:00 +0000)

CPU:   i.MX8MQ rev2.1 1500 MHz (running at 1000 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 35C
Reset cause: POR
Model: NXP i.MX8MQ EVK
DRAM:  3 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from FAT... *** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial

 BuildInfo:
  - ATF c949a88
  - U-Boot 2020.04+fio+gdbb9acc4eb

Net:   
Warning: ethernet@30be0000 using MAC address from ROM
eth0: ethernet@30be0000
3019 bytes read in 8 ms (368.2 KiB/s)
## Executing script at 40480000
sha256,rsa2048:dev+ sha256+ Using freescale_imx8mq-evk.dtb
Saving Environment to FAT... OK
463 bytes read in 10 ms (44.9 KiB/s)
13940582 bytes read in 94 ms (141.4 MiB/s)
## Loading kernel from FIT Image at 43800000 ...
   Using 'conf@freescale_imx8mq-evk.dtb' configuration
   Verifying Hash Integrity ... sha256,rsa2048:dev+ OK
   Trying 'kernel@1' kernel subimage
     Description:  Linux kernel
     Type:         Kernel Image
     Compression:  gzip compressed
     Data Start:   0x4380010c
     Data Size:    9922696 Bytes = 9.5 MiB
     Architecture: AArch64
     OS:           Linux
     Load Address: 0x40480000
     Entry Point:  0x40480000
     Hash algo:    sha256
     Hash value:   59b675b1748d96e4c43665744c3c8ea735702b259de91f0bbf7e40a7a37da1c0
   Verifying Hash Integrity ... sha256+ OK
## Loading ramdisk from FIT Image at 43800000 ...
   Using 'conf@freescale_imx8mq-evk.dtb' configuration
   Verifying Hash Integrity ... sha256,rsa2048:dev+ OK
   Trying 'ramdisk@1' ramdisk subimage
     Description:  initramfs-ostree-lmp-image
     Type:         RAMDisk Image
     Compression:  uncompressed
     Data Start:   0x44204c30
     Data Size:    3420110 Bytes = 3.3 MiB
     Architecture: AArch64
     OS:           Linux
     Load Address: unavailable
     Entry Point:  unavailable
     Hash algo:    sha256
     Hash value:   d11a94656a1079591e029b50b51d8f11c443f833396137c3d844800263e2af39
   Verifying Hash Integrity ... sha256+ OK
## Loading fdt from FIT Image at 43800000 ...
   Using 'conf@freescale_imx8mq-evk.dtb' configuration
   Verifying Hash Integrity ... sha256,rsa2048:dev+ OK
   Trying 'fdt@freescale_imx8mq-evk.dtb' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x441acd04
     Data Size:    43932 Bytes = 42.9 KiB
     Architecture: AArch64
     Load Address: 0x43000000
     Hash algo:    sha256
     Hash value:   61b66954c7944d4fdfe527a28903b42a5c4b4c1fd3b629ddcfaf18182af451ea
   Verifying Hash Integrity ... sha256+ OK
   Loading fdt from 0x441acd04 to 0x43000000
   Booting using the fdt blob at 0x43000000
   Uncompressing Kernel Image
   Using Device Tree in place at 0000000043000000, end 000000004300db9b

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.4.97-lmp-standard (oe-user@oe-host) (gcc version 10.2.0 (GCC)) #1 SMP PREEMPT Tue Mar 9 13:45:00 UTC 2021
[    0.000000] Machine model: NXP i.MX8MQ EVK
[    0.000000] earlycon: ec_imx6q0 at MMIO 0x0000000030860000 (options '115200')
[    0.000000] printk: bootconsole [ec_imx6q0] enabled

```

**Comment by igoropaniuk** [comment]
iMX8MM-EVK
```
U-Boot SPL 2020.04+fio+gdbb9acc4eb (Mar 05 2021 - 02:05:01 +0000)
power_bd71837_init
DDRINFO: start DRAM init
DDRINFO: DRAM rate 3000MTS
DDRINFO:ddrphy calibration done
DDRINFO: ddrmix config done
Normal Boot
Trying to boot from MMC2
NOTICE:  BL31: v2.2(release):rel_imx_5.4.47_2.2.0-0-gc949a888e-dirty
NOTICE:  BL31: Built : 02:10:00, Feb 23 2021
I/TC: 
I/TC: Non-secure external DT found
I/TC: OP-TEE version: 3.10.0-87-g01ed34ee (gcc version 10.2.0 (GCC)) #1 Tue 02 Mar 2021 09:22:13 PM UTC aarch64
I/TC: Primary CPU initializing
I/TC: Primary CPU switching to normal world boot


U-Boot 2020.04+fio+gdbb9acc4eb (Mar 05 2021 - 02:04:57 +0000)

CPU:   i.MX8MMQ rev1.0 1800 MHz (running at 1200 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 37C
Reset cause: POR
Model: NXP i.MX8MM EVK board
DRAM:  2 GiB
TCPC:  Vendor ID [0x1fc9], Product ID [0x5110], Addr [I2C1 0x52]
Power supply on USB2
TCPC:  Vendor ID [0x1fc9], Product ID [0x5110], Addr [I2C1 0x50]
MMC:   FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from FAT... *** Warning - bad CRC, using default environment

[*]-Video Link 0Can't find cec device id=0x3c
fail to probe panel device adv7535@3d
failed to get any video link display timings
probe video device failed, ret -22

	[0] lcdif@32e00000, video
	[1] mipi_dsi@32e10000, video_bridge
	[2] adv7535@3d, panel
Can't find cec device id=0x3c
fail to probe panel device adv7535@3d
failed to get any video link display timings
probe video device failed, ret -22
In:    serial
Out:   serial
Err:   serial

 BuildInfo:
  - ATF c949a88
  - U-Boot 2020.04+fio+gdbb9acc4eb

flash target is MMC:2
Net:   
Warning: ethernet@30be0000 using MAC address from ROM
eth0: ethernet@30be0000
Fastboot: Normal
Hit any key to stop autoboot:  0 
170 bytes read in 6 ms (27.3 KiB/s)
## Executing script at 40480000
387 bytes read in 5 ms (75.2 KiB/s)
44632 bytes read in 10 ms (4.3 MiB/s)
26960384 bytes read in 106 ms (242.6 MiB/s)
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
   Using Device Tree in place at 0000000043000000, end 000000004300de57
Can't find cec device id=0x3c
fail to probe panel device adv7535@3d
failed to get any video link display timings
probe video device failed, ret -22

Starting kernel ...

unable to select a mode
device_remove: Device 'mmc@30b60000.blk' failed to remove, but children are gone
I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot
I/TC: Secondary CPU 2 initializing
I/TC: Secondary CPU 2 switching to normal world boot
I/TC: Secondary CPU 3 initializing
I/TC: Secondary CPU 3 switching to normal world boot
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.4.97-lmp-standard (oe-user@oe-host) (gcc version 10.2.0 (GCC)) #1 SMP PREEMPT Tue Feb 23 02:06:12 UTC 2021
[    0.000000] Machine model: FSL i.MX8MM EVK board

```

**Comment by igoropaniuk** [comment]
@mike-scott @ricardosalveti all good

**Comment by ricardosalveti** [comment]
Awesome, thanks for testing it.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
