### PR TITLE
conf: keys: move platform specific keys

### PR DESCRIPTION
**Pull request by ldts**
Move the default keys to a platform specific directory

### CODE REVIEW

**Comment by angolini** [comment]
I'm not sure how to handle this PR. I understand the goal, but I also think if we are going to organize the keys depending on the architecture/platform, other files could also be organized.

And I'm not sure I completely understand the use of the word "platform" as one directory

**Comment by ricardosalveti** [comment]
Right, platform is indeed confusing based on the way we are currently using other keys.

Other keys are generic and not platform specific, this one (while technically generic) is specific to TI, so having it under a different directory is fine, just not sure if 'platform/ti' or just 'ti'.

**Comment by ricardosalveti** [comment]
If we decide to change https://github.com/foundriesio/lmp-manifest/pull/356 needs to be aligned.

**Comment by ldts** [comment]
I disagree: `platform/ti `is a good enough abstraction - an incremental improvement - whereas` ti` is a bad abstraction.
we could go with a finer granularity based on the root of trust architecture but why bother...

ATM what we have is just badly abstracted. So if you dont like this PR please propose something so we start aligning...

**Comment by ricardosalveti** [comment]
@ldts please include a meta-lmp bump here as https://github.com/foundriesio/meta-lmp/pull/1213 is now merged.

**Pull request merged**
