### PR TITLE
Stable updates (latest NXP BSP, oe-core before rm_work issue, latest nvidia)

### PR DESCRIPTION
**Pull request by ricardosalveti**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by quaresmajose** [comment]
The jailhouse config fragment needs to be global for all kernels because other layers have the jailhouse MACHINE_FEATURES but don't have the correct modules enabled.
That is the case of the `imx8mp-lpddr4`, I am fixing this and push something to meta-lmp when finished.

**Comment by quaresmajose** [comment]
Should be unblocked by https://github.com/foundriesio/meta-lmp/pull/1015

**Review by angolini — APPROVED** [review]

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
