### PR TITLE
WIP: default.xml: update meta-lmp layer

### PR DESCRIPTION
**Pull request by ricardosalveti**
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by mike-scott** [comment]
@ricardosalveti Pushed HiSilicon and RPi3 fixes to https://github.com/foundriesio/linux/commits/linux-v5.0.y
new SHA: 81c2a3c563656aceb2750a58e38dde2e98d4e4ed

**Pull request closed without merging**
