### PR TITLE
Bump for meta-freescale and meta-freescale-3rdparty

### PR DESCRIPTION
**Pull request by angolini**

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]

**Review by quaresmajose — APPROVED** [review]
LGTM

Maybe we need that @angolini patch merged on meta-lmp, at the end the CI job will show if the patch is need or not. In main-next it is required https://github.com/foundriesio/meta-lmp/commit/ac54d203b3d1478f54687d580644badc56dbae44
```
bsp: lmp-machine-custom: Add imx-boot dependency
Needed after https://github.com/Freescale/meta-freescale/commit/bed09c8daec54c73766b563feb9ff7b4168c3e44
```

**Comment by angolini** [comment]
ci-retest

**Comment by angolini** [comment]
ci-retest

**Comment by quaresmajose** [comment]
@angolini can you please bump meta-updater as well on the next rebase of this PR? It will be useful to have https://github.com/uptane/meta-updater/commit/79358972d0e10649051b365e0bc9d7d29522cc73 as it helps debugging some ci build issues.

**Comment by angolini** [comment]
@quaresmajose ok

**Comment by ricardosalveti** [comment]
Can you rebase and also do the meta-updater bump as part of this pr?

**Comment by quaresmajose** [comment]
> Can you also do the meta-updater bump as part of this pr?

As it builds fine for every target I think we can merge it as is and we bump the meta-updater in another PR

**Pull request merged**
